server:
  port: 8080
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-alias: keystore
    key-store: /config/keystore.p12
    key-store-password: ${KEY_STORE_PASSWORD}
    key-password: ${KEY_PASSWORD}
#    trust-store-type: PKCS12
#    trust-store: /config/truststore.p12
#    trust-store-password: ${TRUST_STORE_PASSWORD}
spring:
  application:
    name: api-gateway
  config:
    import: configserver:https://lsa-config-service:9999/
  cloud:
    config:
      uri: https://lsa-config-service:9999/
      tls:
        enabled: true
        key-store-type: PKCS12
        key-alias: keystore
        key-store: /config/keystore.p12
        key-store-password: ${KEY_STORE_PASSWORD}
        key-password: ${KEY_PASSWORD}
#        trust-store-type: PKCS12
#        trust-store: /config/truststore.p12
#        trust-store-password: ${TRUST_STORE_PASSWORD}
#trust:
#  store: /config/keystore.p12
#  store.password: ${TRUST_STORE_PASSWORD}