server:
  port: 8080
spring:
  application:
    name: api-gateway

spring.cloud:
  bootstrap:
    enabled: true

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: https://service-registry:8761/eureka/
