server:
  port: 8080
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-alias: keystore
    key-store: /config/keystore.p12
    key-store-password: ${KEY_STORE_PASSWORD}
    key-password: ${KEY_PASSWORD}
spring:
  application:
    name: api-gateway

spring.cloud:
  bootstrap:
    enabled: true

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: https://service-registry:8761/eureka/
