server:
  port: 8080
spring:
  config:
    import: configserver:http://lsa-config-service:9999/
  application:
    name: api-gateway
  cloud:
    config:
      username: ${CONFIG_USERNAME}
      password: ${CONFIG_PASSWORD}
