server:
  port: 8080
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-alias: keystore
    key-store: ${KEY_STORE_PATH}
    key-store-password: ${KEY_STORE_PASSWORD}
    key-password: ${KEY_PASSWORD}
spring:
  application:
    name: api-gateway

spring.cloud:
  bootstrap:
    enabled: true

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI}
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
