server:
  port: 5001
spring:
  application:
    name: event-service
  config:
    import: configserver:http://lsa-config-service:9999/
  cloud:
    config:
      username: ${CONFIG_USERNAME}
      password: ${CONFIG_PASSWORD}