server:
  port: 8086
spring:
  cloud:
    gateway:
      redis:
        enabled: false
      routes:
        - id: quotes
          uri: http://localhost:8085
          predicates:
            - Path=/quotes/**
          filters:
            - TokenRelay=
        - id: quotes
          uri: http://localhost:5001
          predicates:
            - Path=/api/event/**
          filters:
            - TokenRelay=
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8083/auth/realms/lsa
        registration:
          quotes-client:
            provider: keycloak
            client-id: quotes-client
            client-secret: 0e082231-a70d-48e8-b8a5-fbfb743041b6
            scope:
              - openid
              - email
              - profile
              - roles
<<<<<<< HEAD

          event-service:
            provider: keycloak
            client-id: event-service
            redirect-uri-template: "localhost:8083/auth/realms/lsa/"
            client-secret: x7cLVF4WiGCrSXclHjNk0VZDMR9OlxMh
=======
---
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8083/auth/realms/lsa
        registration:
          event-service:
            provider: keycloak
            client-id: event-service
            client-secret: 3F2275wzaP7AkhEIeiOjePffT8eYruFs
>>>>>>> security5
            scope:
              - openid
              - email
              - profile
              - roles
<<<<<<< HEAD

  cloud:
    gateway:
      redis:
        enabled: false
      routes:
        - id: quotes
          uri: http://localhost:8085
          predicates:
            - Path=/quotes/**
          filters:
            - TokenRelay=
        - id: quotes
          uri: http://localhost:5001
          predicates:
            - Path=/api/event/**
          filters:
            - TokenRelay=
=======
>>>>>>> security5
