spring:
  cloud:
    bootstrap:
      enabled: true
eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: https://service-registry:8761
  instance:
    hostname: service-registry
server:
  port: 8761
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-alias: keystore
    key-store: /config/keystore.p12
    key-store-password: ${KEY_STORE_PASSWORD}
    key-password: ${KEY_PASSWORD}
