spring:
  config:
    import: optional:configserver:https://www.turbolessons.com:9999/
eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: https://www.turbolessons.com:8761
  instance:
    hostname: service-registry
server:
  port: 8761
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-alias: keystore
    key-store: classpath:/config/keystore.p12
    key-store-password: ${KEY_STORE_PASSWORD}
    key-password: ${KEY_PASSWORD}
