server:
  port: 8761
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-alias: keystore
    key-store: /config/keystore.p12
    key-store-password: ${KEY_STORE_PASSWORD}
    key-password: ${KEY_PASSWORD}
spring:
  application:
    name: service-registry
  security:
    user:
      name: ${EUREKA_USERNAME}
      password: ${EUREKA_PASSWORD}
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring.cloud:
  bootstrap:
    enabled: true

logging:
  level:
    org:
      springframework:
        security: DEBUG

eureka:
  client:
    secure-port-enabled: true
    secure-port: 8761
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: ${EUREKA_URI}
  server:
    waitTimeInMsWhenSyncEmpty: 0