server:
  port: 8761
  ssl:
    keyAlias: keystore
    enabled: true
    keyStore: ${KEY_STORE_PATH}
    trustStore: ${TRUST_STORE_PATH}
    keyStoreType: PKCS12
    keyStorePassword: ${KEY_STORE_PASSWORD}
    trustStorePassword: ${TRUST_STORE_PASSWORD}
    keyPassword: ${KEY_PASSWORD}
spring:
  config:
    import: optional:configserver:https://lsa-config-service:9999/
  application:
    name: service-registry
  security:
    user:
      name: ${EUREKA_USERNAME}
      password: ${EUREKA_PASSWORD}
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org:
      springframework:
        security: DEBUG

eureka:
  instance:
    hostname: service-registry
    metadataMap:
      user: ${EUREKA_USERNAME}
      password: ${EUREKA_PASSWORD}
  client:
    securePortEnabled: true
    securePort: 8761
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: https://${eureka.instance.hostname}:${server.port}/eureka/