eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: https://service-registry:8761
  instance:
    hostname: service-registry
server:
  port: 8761
  ssl:
    key-store-type: PKCS12
    key-store: /tmp/www.turbolessons.com.p12
    key-store-password: ${KEY_STORE_PASSWORD}
    key-alias: www.turbolessons.com
