spring:
  config:
    import: optional:configserver:https://lsa-config-service:9999/
  cloud:
    config:
      uri: https://lsa-config-service:9999/
      tls:
        enabled: true
        key-store-type: PKCS12
        key-alias: keystore
        key-store: classpath:/ssl/keystore.p12
        key-store-password: ${KEY_STORE_PASSWORD}
        key-password: ${KEY_PASSWORD}
        trust-store-type: PKCS12
        trust-store: classpath:/ssl/truststore.p12
        trust-store-password: ${TRUST_STORE_PASSWORD}
eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: https://service-registry:8761
  instance:
    hostname: service-registry
server:
  port: 8761
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-alias: keystore
    key-store: classpath:/ssl/keystore.p12
    key-store-password: ${KEY_STORE_PASSWORD}
    key-password: ${KEY_PASSWORD}
    trust-store-type: PKCS12
    trust-store: classpath:/ssl/truststore.p12
    trust-store-password: ${TRUST_STORE_PASSWORD}
trust:
  store: classpath:/ssl/keystore.p12
  store.password: ${TRUST_STORE_PASSWORD}