server:
  port: 8761
  ssl:
    keyAlias: keystore
    enabled: true
    keyStore: ${KEY_STORE_PATH}
    trustStore: ${TRUST_STORE_PATH}
    keyStoreType: PKCS12
    keyStorePassword: ${KEY_STORE_PASSWORD}
    trustStorePassword: ${TRUST_STORE_PASSWORD}
    keyPassword: ${KEY_PASSWORD}
spring:
  application:
    name: service-registry
  security:
    user:
      name: ${EUREKA_USERNAME}
      password: ${EUREKA_PASSWORD}
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring.cloud:
  bootstrap:
    enabled: true

logging:
  level:
    org:
      springframework:
        security: DEBUG

eureka:
  client:
    secure-port-enabled: true
    secure-port: 8761
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: ${EUREKA_URI}
  server:
    waitTimeInMsWhenSyncEmpty: 0