server.port: 5005
spring:
    main:
        allow-bean-definition-overriding: true
    application:
        name: message-service
    config:
        import: configserver:http://localhost:9999
    data:
        mongodb:
            uri: mongodb://localhost:27017/lsa_message_plt
