spring:
  application:
    name: message-service
  cloud:
    config:
      username: ${CONFIG_USERNAME}
      password: ${CONFIG_PASSWORD}
  config:
    import: configserver:http://lsa-config-service:9999/


