version: "2"
networks:
  keycloak-network:
services:
  keycloak:
    image: com-noslen-authorization-server:latest
    container_name: keycloak
    environment:
      KEYCLOAK_USER: noslen
      KEYCLOAK_PASSWORD: pass
      KEYCLOAK_REALM: lsa
      DB_ADDR: mysql
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      DB_PORT: "3306"
      DB_DATABASE: keycloak
    ports:
      - "8083:8083"
    networks:
      - keycloak-network
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
      MYSQL_DATABASE: keycloak
    ports:
      - "3306:3306"
    networks:
      - keycloak-network