server:
  port: 9999
spring:
  application:
    name: config-server
  cloud:
    config:
      discovery:
        enabled: true
      server:
        bootstrap: true
        git:
          default-label: main
          uri: https://github.com/ntjohns1/lsa-config.git
  management:
    security:
      enabled: false
management:
  endpoints:
    web:
      exposure:
        include: '*'
