server:
  port: 9999
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-alias: keystore
    key-store: ${KEY_STORE_PATH}
    key-store-password: ${KEY_STORE_PASSWORD}
    key-password: ${KEY_PASSWORD}
spring:
  application:
    name: lsa-config-service
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: https://service-registry:8761/eureka/