encrypt:
  key: SoGk99F1INl7Shp2pYQQPNzFfL+vdHhP8x9VlLLlg8Ok
spring:
  application:
    name: lsa-config-service
  cloud:
    config:
      server:
        bootstrap: false
        git:
          default-label: main
          uri: https://github.com/ntjohns1/lsa-config.git
      discovery:
        enabled: true
server:
  port: 9999
  ssl:
    enabled: true
    key-store: ${KEY_STORE_PATH}
    key-store-type: PKCS12
    key-store-password: ${KEY_STORE_PASSWORD}
    key-password: ${KEY_PASSWORD}
    trust-store: ${TRUST_STORE_PATH}
    trust-store-type: PKCS12
    trust-store-password: ${TRUST_STORE_PASSWORD}


management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: 8761
  client:
    register-with-eureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI}
    tls:
      enabled: true
      key-store: ${KEY_STORE_PATH}
      key-store-type: PKCS12
      key-store-password: ${KEY_STORE_PASSWORD}
      key-password: ${KEY_PASSWORD}
      trust-store: ${TRUST_STORE_PATH}
      trust-store-type: PKCS12
      trust-store-password: ${TRUST_STORE_PASSWORD}
