encrypt:
  key: SoGk99F1INl7Shp2pYQQPNzFfL+vdHhP8x9VlLLlg8Ok
server:
  port: 9999
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-alias: keystore
    key-store: ${KEY_STORE_PATH}
    key-store-password: ${KEY_STORE_PASSWORD}
    key-password: ${KEY_PASSWORD}
    trustStore: ${TRUST_STORE_PATH}
    trustStorePassword: ${TRUST_STORE_PASSWORD}

spring:
  application:
    name: lsa-config-service
  cloud:
    config:
      server:
        bootstrap: true
        git:
          default-label: main
          uri: https://github.com/ntjohns1/lsa-config.git
      discovery:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    secure-port-enabled: true
    secure-port: 8761
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI}
    tls:
      enabled: true
      keyStore: ${KEY_STORE_PATH}
      trustStore: ${TRUST_STORE_PATH}
      keyStoreType: PKCS12
      keyStorePassword: ${KEY_STORE_PASSWORD}
      trustStorePassword: ${TRUST_STORE_PASSWORD}
      keyPassword: ${KEY_PASSWORD}