encrypt:
  key: SoGk99F1INl7Shp2pYQQPNzFfL+vdHhP8x9VlLLlg8Ok
server:
  port: 9999
  ssl:
    key-store-type: PKCS12
    key-store: /config/www.turbolessons.com.p12
    key-store-password: ${KEY_STORE_PASSWORD}
    key-alias: www.turbolessons.com
    enabled: true
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        bootstrap: true
        git:
          default-label: main
          uri: https://github.com/ntjohns1/lsa-config.git
      discovery:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'