encrypt:
  key: SoGk99F1INl7Shp2pYQQPNzFfL+vdHhP8x9VlLLlg8Ok
server:
  port: 9999
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-alias: keystore
    key-store: ${KEY_STORE_PATH}
    key-store-password: ${KEY_STORE_PASSWORD}
    key-password: ${KEY_PASSWORD}
spring:
  application:
    name: lsa-config-service
  cloud:
    config:
      server:
        bootstrap: true
        git:
          default-label: main
          uri: https://github.com/ntjohns1/lsa-config.git
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
      discovery:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: https://service-registry:8761/eureka/