encrypt:
  keyStore:
    location: classpath:/server.p12
    password: letmein
    alias: mytestkey
    secret: letmein
    type: PKCS12
server:
  port: 9999
spring:
  application:
    name: config-server
  security:
    user:
      name: test
      password: pass
  cloud:
    config:
      discovery:
        enabled: true
      server:
        bootstrap: true
        git:
          default-label: main
          uri: https://github.com/ntjohns1/lsa-config.git
  management:
    security:
      enabled: false
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    org.springframework.cloud: DEBUG