encrypt:
  key: SoGk99F1INl7Shp2pYQQPNzFfL+vdHhP8x9VlLLlg8Ok
server:
  port: 9999
  ssl:
    key-alias: www.turbolessons.com
    key-store: /tmp/www.turbolessons.com.keystore
    key-store-password: ${KEY_STORE_PASSWORD}
    key-password: ${KEY_PASSWORD}
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        bootstrap: true
        git:
          default-label: main
          uri: https://github.com/ntjohns1/lsa-config.git
management:
  endpoints:
    web:
      exposure:
        include: '*'