server:
  port: 5010
spring:
  application:
    name: payment-service
  cloud:
    config:
      username: ${CONFIG_USERNAME}
      password: ${CONFIG_PASSWORD}
  config:
    import: configserver:http://www.turbolessons.com:9999/
