spring:
    application:
        name: event-service
    config:
        import: configserver:http://localhost:9999
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/