version: "3.9"
networks:
  lsa-cloud-service_lsa:
  email-service_lsa:
  event-service_lsa:
  message-service_lsa:
services:
  lsa-config-service:
    image: noslenj/lsa-config-service:com-noslen-lsa-config-service
    container_name: lsa-config-service
    env_file:
      - ./root.env
    volumes:
      - config_keystore:/config
    ports:
      - "9999:9999"
    networks:
      - lsa-cloud-service_lsa
  service-registry:
    image: noslenj/service-registry:com-noslen-service-registry
    container_name: service-registry
    env_file:
      - ./root.env
    ports:
      - "8761:8761"
    networks:
      - lsa-cloud-service_lsa
  admin-service:
    image: noslenj/admin-service:com-noslen-admin-service
    container_name: admin-service
    env_file:
      - ./root.env
    ports:
      - "5002:5002"
    networks:
      - lsa-cloud-service_lsa
  email-service:
    image:  noslenj/email-service:com-noslen-email-service
    container_name: email-service
    volumes:
      - emaildb_data:/data/db
      - ./template-thymeleaf.html:/app/mail-templates
    ports:
      - "5003:5003"
    networks:
      - lsa-cloud-service_lsa
      - email-service_lsa
  emaildb:
    image: mongo:latest
    container_name: emaildb
    env_file:
      - ./root.env
    ports:
      - "5053:27017"
    networks:
      - lsa-cloud-service_lsa
      - email-service_lsa
  event-service:
    image: noslenj/event-service:com-noslen-event-service
    container_name: event-service
    env_file:
      - ./root.env
    volumes:
      - lessondb_data:/var/lib/mysql
    ports:
      - "5001:5001"
    networks:
      - lsa-cloud-service_lsa
      - event-service_lsa
  lessondb:
    image: noslenj/lessondb:com-noslen-lessondb
    container_name: lessondb
    env_file:
      - ./root.env
    ports:
      - "5051:3306"
    networks:
      - lsa-cloud-service_lsa
      - event-service_lsa
  message-service:
    image: noslenj/message-service:com-noslen-message-service
    container_name: message-service
    env_file:
      - ./root.env
    ports:
      - "5005:5005"
    networks:
      - lsa-cloud-service_lsa
      - message-service_lsa
  messagedb:
    image: mongo:latest
    container_name: messagedb
    restart: always
    env_file:
      - ./root.env
    volumes:
      - messagedb_data:/data/db
    ports:
      - "5055:27017"
    networks:
      - lsa-cloud-service_lsa
      - message-service_lsa
  video-service:
    image: noslenj/video-service:com-noslen-video-service
    container_name: video-service
    env_file:
      - ./root.env
    volumes:
      - ./gcs:/gcs
    ports:
      - "5004:5004"
    networks:
      - lsa-cloud-service_lsa
  api-gateway:
    image: noslenj/api-gateway:com-noslen-api-gateway
    container_name: api-gateway
    env_file:
      - ./root.env
    ports:
      - "8080:8080"
    networks:
      - lsa-cloud-service_lsa
  lsa-frontend:
    image: noslenj/lsa-frontend:lsa-frontend
    container_name: lsa-frontend
    env_file:
      - ./root.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./pem_files/fullchain.pem:/etc/letsencrypt/live/www.turbolessons.com/fullchain.pem
      - ./pem_files/privkey.pem:/etc/letsencrypt/live/www.turbolessons.com/privkey.pem
      - ./nginx:/etc/letsencrypt
      - ./LSA_Frontend/lsa-frontend/nginx.conf:/etc/nginx/nginx.conf
      - ./LSA_Frontend/lsa-frontend/mime.types:/etc/nginx/mime.types
    networks:
      - lsa-cloud-service_lsa
volumes:
  emaildb_data:
  lessondb_data:
  messagedb_data:
  config_keystore:

