version: "3.9"
networks:
  lsa-cloud-service_lsa:
services:
  lsa-config-service:
    image: com-noslen-config-service:latest
    container_name: lsa-config-service
    hostname: config-service
    expose:
      - "9999"
    ports:
      - "9999:9999"
    networks:
      - lsa-cloud-service_lsa
  service-registry:
    image: com-noslen-service-registry:latest
    container_name: service-registry
    hostname: service-registry
    environment:
      eureka.instance.preferIpAddress: 1
      eureka.instance.ip-address: 172.19.0.4
      eureka.client.serviceUrl.defaultZone: http://service-registry:8761/eureka
    expose:
      - "8761"
    ports:
      - "8761:8761"
    networks:
      - lsa-cloud-service_lsa
    depends_on:
      - lsa-config-service



