version: "3.9"
networks:
  lsa-cloud-service_lsa:
  email-service_lsa:
  event-service_lsa:
  message-service_lsa:
services:
  lsa-config-service:
    image: noslenj/lsa-config-service:latest
    container_name: lsa-config-service
    env_file:
      - ./root.env
    volumes:
      - ./keystores/config.p12:/config/config.p12
      - config_keystore:/config
    ports:
      - "9999:9999"
    networks:
      - lsa-cloud-service_lsa
  service-registry:
    image: noslenj/service-registry:latest
    container_name: service-registry
    env_file:
      - ./root.env
    ports:
      - "8761:8761"
    networks:
      - lsa-cloud-service_lsa
  admin-service:
    image: noslenj/admin-service:latest
    container_name: admin-service
    env_file:
      - ./root.env
    ports:
      - "5002:5002"
    networks:
      - lsa-cloud-service_lsa
  email-service:
    image:  noslenj/email-service:latest
    container_name: email-service
    volumes:
      - emaildb_data:/data/db
      - ./template-thymeleaf.html:/app/mail-templates
    ports:
      - "5003:5003"
    networks:
      - lsa-cloud-service_lsa
      - email-service_lsa
    depends_on:
      - emaildb
  emaildb:
    image: mongo:latest
    container_name: emaildb
    env_file:
      - ./root.env
    ports:
      - "5053:27017"
    networks:
      - lsa-cloud-service_lsa
      - email-service_lsa
  event-service:
    image: noslenj/event-service:latest
    container_name: event-service
    env_file:
      - ./root.env
    volumes:
      - lessondb_data:/var/lib/mysql
    ports:
      - "5001:5001"
    networks:
      - lsa-cloud-service_lsa
      - event-service_lsa
  lessondb:
    image: noslenj/lessondb:latest
    container_name: lessondb
    env_file:
      - ./root.env
    ports:
      - "5051:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - lessondb_data:/var/lib/mysql
    networks:
      - lsa-cloud-service_lsa
      - event-service_lsa
  message-service:
    image: noslenj/message-service:latest
    container_name: message-service
    env_file:
      - ./root.env
    ports:
      - "5005:5005"
    networks:
      - lsa-cloud-service_lsa
      - message-service_lsa
    depends_on:
      - messagedb
  messagedb:
    image: mongo:latest
    container_name: messagedb
    restart: always
    env_file:
      - ./root.env
    volumes:
      - messagedb_data:/data/db
    ports:
      - "5055:27017"
    networks:
      - lsa-cloud-service_lsa
      - message-service_lsa
  video-service:
    image: noslenj/video-service:latest
    container_name: video-service
    env_file:
      - ./root.env
    volumes:
      - ./gcs:/gcs
    ports:
      - "5004:5004"
    networks:
      - lsa-cloud-service_lsa
  api-gateway:
    image: noslenj/api-gateway:latest
    container_name: api-gateway
    env_file:
      - ./root.env
    ports:
      - "8080:8080"
    networks:
      - lsa-cloud-service_lsa
  turbolessons-frontend:
    image: noslenj/turbolessons-frontend:latest
    container_name: turbolessons-frontend
    env_file:
      - ./root.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./pem_files/fullchain.pem:/etc/letsencrypt/live/www.turbolessons.com/fullchain.pem
      - ./pem_files/privkey.pem:/etc/letsencrypt/live/www.turbolessons.com/privkey.pem
      - ./nginx:/etc/letsencrypt
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./mime.types:/etc/nginx/mime.types
    networks:
      - lsa-cloud-service_lsa
volumes:
  emaildb_data:
  lessondb_data:
  messagedb_data:
  config_keystore:

