version: "2"
networks:
 keycloak-network:
services:
  keycloak:
    image: com-noslen-authorization-server:latest
    container_name: keycloak
    environment:
      KEYCLOAK_USER: noslen
      KEYCLOAK_PASSWORD: pass
      KEYCLOAK_REALM: lsa
      DB_ADDR: mysql
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      DB_PORT: "3306"
      DB_DATABASE: keycloak
    ports:
      - "8083:8083"
    networks:
      - keycloak-network
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
      MYSQL_DATABASE: keycloak
    ports:
      - "3306:3306"
    networks:
      - keycloak-network
  config-service:
    image: com-noslen-lsa-config-service:latest
    container_name: config-server
    ports:
      - "9999:9999"
  service-registry:
    image: com-noslen-service-registry:latest
    container_name: service-registry
    ports:
      - "8761:8761"
    depends_on:
      - config-service
  gateway:
    image: com-noslen-gateway-service:latest
    container_name: gateway
    expose:
      - "8086"
    ports:
      - "8086:8086"
    depends_on:
      - keycloak
  event-service:
    image: com-noslen-event-service:latest
    container_name: event-service
    expose:
      - "5001"
    ports:
      - "5001:5001"

