version: "3.9"
networks:
  lsa-cloud-service_lsa:
  email-service_lsa:
  event-service_lsa:
  message-service_lsa:
services:
  lsa-config-service:
    image: noslenj/lsa-config-service:com-noslen-lsa-config-service
    container_name: lsa-config-service
    env_file:
      - ./root.env
    volumes:
      - config-keystore:/config
    ports:
      - "9999:9999"
    networks:
      - lsa-cloud-service_lsa
  service-registry:
    image: noslenj/service-registry:com-noslen-service-registry
    container_name: service-registry
    env_file:
      - ./root.env
    ports:
      - "8761:8761"
    networks:
      - lsa-cloud-service_lsa
  admin-service:
    image: noslenj/admin-service:com-noslen-admin-service
    container_name: admin-service
    env_file:
      - ./root.env
#    volumes:
#      - ./keystore:/config
    ports:
      - "5002:5002"
    networks:
      - lsa-cloud-service_lsa
  email-service:
    image:  noslenj/email-service:com-noslen-email-service
    container_name: email-service
    volumes:
      - emaildb_data:/data/db
      - ./keystore/keystore.p12:/config/keystore.p12
      - ./truststore/truststore.p12:/config/truststore.p12
      - ./template-thymeleaf.html:/app/mail-templates
    ports:
      - "5003:5003"
    networks:
      - lsa-cloud-service_lsa
      - email-service_lsa
  emaildb:
    image: mongo:latest
    container_name: emaildb
    volumes:
      - ./keystore/keystore.p12:/config/keystore.p12
      - ./truststore/truststore.p12:/config/truststore.p12
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_AUTH_SOURCE: admin
    ports:
      - "5053:27017"
    networks:
      - lsa-cloud-service_lsa
      - email-service_lsa
  event-service:
    image: noslenj/event-service:com-noslen-event-service
    container_name: event-service
    volumes:
      - lessondb_data:/var/lib/mysql
      - ./keystore/keystore.p12:/config/keystore.p12
      - ./truststore/truststore.p12:/config/truststore.p12
    ports:
      - "5001:5001"
    networks:
      - lsa-cloud-service_lsa
      - event-service_lsa
  lessondb:
    image: noslenj/lessondb:com-noslen-lessondb
    container_name: lessondb
    volumes:
      - ./keystore/keystore.p12:/config/keystore.p12
      - ./truststore/truststore.p12:/config/truststore.p12
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: eventplt
    ports:
      - "5051:3306"
    networks:
      - lsa-cloud-service_lsa
      - event-service_lsa
  message-service:
    image: noslenj/message-service:com-noslen-message-service
    container_name: message-service
    env_file:
      - ./root.env
    volumes:
      - ./keystore/keystore.p12:/config/keystore.p12
      - ./truststore/truststore.p12:/config/truststore.p12
    ports:
      - "5005:5005"
    networks:
      - lsa-cloud-service_lsa
      - message-service_lsa
  messagedb:
    image: mongo:latest
    container_name: messagedb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_AUTH_SOURCE: admin
    volumes:
      - messagedb_data:/data/db
      - ./keystore.p12:/config/keystore.p12
    ports:
      - "5055:27017"
    networks:
      - lsa-cloud-service_lsa
      - message-service_lsa
  video-service:
    image: noslenj/video-service:com-noslen-video-service
    container_name: video-service
    environment:
      projectId: lesson-schedule-assistant
      credentialsPath: /lesson-schedule-assistant-cfe4cf3aebad.json
      bucketName: noslen-test-bucket
    volumes:
      - ./lesson-schedule-assistant-cfe4cf3aebad.json:/lesson-schedule-assistant-cfe4cf3aebad.json
      - ./keystore/keystore.p12:/config/keystore.p12
      - ./truststore/truststore.p12:/config/truststore.p12
    ports:
      - "5004:5004"
    networks:
      - lsa-cloud-service_lsa
  api-gateway:
    image: noslenj/api-gateway:com-noslen-api-gateway
    container_name: api-gateway
    env_file:
      - ./root.env
#    volumes:
#      - ./keystore:/config
    ports:
      - "8080:8080"
    networks:
      - lsa-cloud-service_lsa
  lsa-frontend:
    image: noslenj/lsa-frontend:lsa-frontend
    container_name: lsa-frontend
    env_file:
      - ./root.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
#      - ./keystore/keystore.p12:/config/keystore.p12
#      - ./truststore/truststore.p12:/config/truststore.p12
      - /etc/letsencrypt/live/www.turbolessons.com/fullchain.pem:/etc/letsencrypt/live/www.turbolessons.com/fullchain.pem
      - /etc/letsencrypt/live/www.turbolessons.com/privkey.pem:/etc/letsencrypt/live/www.turbolessons.com/privkey.pem
      - /etc/letsencrypt/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf
      - /etc/letsencrypt/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem
      - ./LSA_Frontend/lsa-frontend/nginx.conf:/etc/nginx/nginx.conf
      - ./LSA_Frontend/lsa-frontend/mime.types:/etc/nginx/mime.types
    networks:
      - lsa-cloud-service_lsa
volumes:
  emaildb_data:
  lessondb_data:
  messagedb_data:
  config_keystore:

