version: "3.9"
networks:
  lsa-cloud-service_lsa:
  email-service_lsa:
  event-service_lsa:
  message-service_lsa:
services:
  lsa-config-service:
    image: noslenj/lsa-config-service:com-noslen-lsa-config-service
    container_name: lsa-config-service
    volumes:
      - /etc/letsencrypt/live/www.turbolessons.com:/etc/letsencrypt/live/www.turbolessons.com
    expose:
      - "9999"
    ports:
      - "9999:9999"
    networks:
      - lsa-cloud-service_lsa
  service-registry:
    image: noslenj/service-registry:com-noslen-service-registry
    container_name: service-registry
    volumes:
      - /etc/letsencrypt/live/www.turbolessons.com:/etc/letsencrypt/live/www.turbolessons.com
    expose:
      - "8761"
    ports:
      - "8761:8761"
    networks:
      - lsa-cloud-service_lsa
    depends_on:
      - lsa-config-service
  admin-service:
    image: noslenj/admin-service:com-noslen-admin-service
    container_name: admin-service
    volumes:
      - /etc/letsencrypt/live/www.turbolessons.com:/etc/letsencrypt/live/www.turbolessons.com
    expose:
      - "5002"
    ports:
      - "5002:5002"
    networks:
      - lsa-cloud-service_lsa
    depends_on:
      - service-registry
  email-service:
    image:  noslenj/email-service:com-noslen-email-service
    container_name: email-service
    volumes:
      - emaildb_data:/data/db
      - /etc/letsencrypt/live/www.turbolessons.com:/etc/letsencrypt/live/www.turbolessons.com
    expose:
      - "5003"
    ports:
      - "5003:5003"
    networks:
      - lsa-cloud-service_lsa
      - email-service_lsa
    depends_on:
      - emaildb
  emaildb:
    image: mongo:latest
    container_name: emaildb
    volumes:
      - /etc/letsencrypt/live/www.turbolessons.com:/etc/letsencrypt/live/www.turbolessons.com
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_AUTH_SOURCE: admin
    expose:
      - "5053"
    ports:
      - "5053:27017"
    networks:
      - lsa-cloud-service_lsa
      - email-service_lsa
    depends_on:
      - admin-service
  event-service:
    image: noslenj/event-service:com-noslen-event-service
    container_name: event-service
    volumes:
      - lessondb_data:/var/lib/mysql
      - /etc/letsencrypt/live/www.turbolessons.com:/etc/letsencrypt/live/www.turbolessons.com
    expose:
      - "5001"
    ports:
      - "5001:5001"
    networks:
      - lsa-cloud-service_lsa
      - event-service_lsa
    depends_on:
      - lessondb
  lessondb:
    image: mysql:latest
    container_name: lessondb
    volumes:
      - /etc/letsencrypt/live/www.turbolessons.com:/etc/letsencrypt/live/www.turbolessons.com
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: eventplt
    expose:
      - "5051"
    ports:
      - "5051:3306"
    networks:
      - lsa-cloud-service_lsa
      - event-service_lsa
    depends_on:
      - email-service
  message-service:
    image: noslenj/message-service:com-noslen-message-service
    container_name: message-service
    volumes:
      - /etc/letsencrypt/live/www.turbolessons.com:/etc/letsencrypt/live/www.turbolessons.com
    expose:
      - "5005"
    ports:
      - "5005:5005"
    networks:
      - lsa-cloud-service_lsa
      - message-service_lsa
    depends_on:
      - messagedb
  messagedb:
    image: mongo:latest
    container_name: messagedb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_AUTH_SOURCE: admin
    volumes:
      - messagedb_data:/data/db
      - /etc/letsencrypt/live/www.turbolessons.com:/etc/letsencrypt/live/www.turbolessons.com
    expose:
      - "5055"
    ports:
      - "5055:27017"
    networks:
      - lsa-cloud-service_lsa
      - message-service_lsa
    depends_on:
      - event-service
  video-service:
    image: noslenj/video-service:com-noslen-video-service
    container_name: video-service
    environment:
      projectId: lesson-schedule-assistant
      credentialsPath: /usr/local/lib/google-cloud/lesson-schedule-assistant-cfe4cf3aebad.json
      bucketName: noslen-test-bucket
    volumes:
      - /Users/noslen/DevProjects/LSA-Cloud-Service/lsa-cloud-service/:/usr/local/lib/lsa-cloud-service
      - /Users/noslen/DevProjects/google-cloud/:/usr/local/lib/google-cloud
      - /etc/letsencrypt/live/www.turbolessons.com:/etc/letsencrypt/live/www.turbolessons.com
    expose:
      - "5004"
    ports:
      - "5004:5004"
    networks:
      - lsa-cloud-service_lsa
    depends_on:
      - message-service
  api-gateway:
    image: noslenj/api-gateway:com-noslen-api-gateway
    container_name: api-gateway
    volumes:
      - /etc/letsencrypt/live/www.turbolessons.com:/etc/letsencrypt/live/www.turbolessons.com
    expose:
      - "443"
    ports:
      - "443:443"
    networks:
      - lsa-cloud-service_lsa
    depends_on:
      - video-service
  lsa-frontend:
    image: noslenj/lsa-frontend:lsa-frontend
    container_name: lsa-frontend
    ports:
      - "3000:80"
    volumes:
      - /Users/noslen/DevProjects/LSA_Frontend/lsa-frontend/okta.env:/app/okta.env
      - /etc/letsencrypt/live/www.turbolessons.com:/etc/letsencrypt/live/www.turbolessons.com
    networks:
      - lsa-cloud-service_lsa
    depends_on:
      - api-gateway
volumes:
  emaildb_data:
  lessondb_data:
  messagedb_data:

