name: email-service-docker

on:
  push:
    paths:
      - "lsa-cloud-service/email-service/**"

jobs:
  docker:
    runs-on: ubuntu-latest

    env:
      OKTA_CLIENT_ID: ${{ secrets.OKTA_CLIENT_ID }}
      OKTA_CLIENT_SECRET: ${{ secrets.OKTA_CLIENT_SECRET }}
      OKTA_ISSUER: ${{ secrets.OKTA_ISSUER }}
      EMAIL_SECRET: ${{ secrets.EMAIL_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push email-service
        uses: docker/build-push-action@v4
        with:
          context: ./lsa-cloud-service/email-service
          push: false
          tags: noslenj/email-service:latest
