name: message-service-docker

on:
  push:
    paths:
      - 'lsa-cloud-service/message-service/**'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2


      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push message-service
        uses: docker/build-push-action@v4
        with:
          context: ./lsa-cloud-service/message-service
          push: true
          tags: noslenj/message-service:latest
