name: video-service-test

on:
  push:
    paths:
      - "lsa-cloud-service/video-service/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:

    - name: Set up JDK 17
      uses: actions/setup-java@v3.12.0
      with:
        distribution: 'adopt'
        java-version: '17'
    
    - name: Checkout code
      uses: actions/checkout@v3.6.0
      
    - name: Decode and create GCP config file
      run: |
        sudo mkdir -p /gcs/
        sudo chown -R runner:runner /gcs/
        echo "${{ secrets.GCS_CONFIG }}" | base64 --decode > /gcs/lesson-schedule-assistant-cfe4cf3aebad.json
        
    - name: Create test file and set permissions
      run: |
        mkdir -p ~/Movies
        touch ~/Movies/Good_Boy.mp4
        chmod 777 ~/Movies/Good_Boy.mp4

    # - name: Set ownership for GCP config directory
    #   run: |
    #     sudo chown -R runner:runner /gcs/

    # - name: Set permissions for GCP config directory
    #   run: |
    #     sudo chmod -R 755 /gcs/
      
    # - name: Set permissions for GCP config file
    #   run: |
    #     sudo chmod 644 /gcs/lesson-schedule-assistant-cfe4cf3aebad.json

    
    - name: Run Maven Tests
      working-directory: ./lsa-cloud-service/video-service
      run: |
        mvn test -DOKTA_CLIENT_ID=${{ secrets.OKTA_CLIENT_ID }} \
        -DOKTA_CLIENT_SECRET=${{ secrets.OKTA_CLIENT_SECRET }} \
        -DOKTA_ISSUER=${{ secrets.OKTA_ISSUER }} \
        -DprojectId=${{ secrets.PROJECT_ID }} \
        -DcredentialsPath=${{ secrets.CREDENTIALS_PATH }} \
        -DbucketName=${{ secrets.BUCKET_NAME }}

